learning_users/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

#Tis appp name is for TEMPLATE linking
app_name='basicapp'

urlpatterns=[
    url(r'^register/$',views.register,name="register"),
    url(r'^user_login/$',views.user_login,name="user_login"),
]

learning_users/learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basicapp import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^basicapp/',include('basicapp.urls')),
    url(r'^logout/$',views.user_logout,name="user_logout"),
    url(r'^special/$',views.special,name="special"),
]

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User)
    #Addition attributes
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to="profile_pics",blank=True)

    def __str__(self):
        return self.user.username

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import *

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    username=forms.CharField(max_length=120)

    class Meta():
        model=User
        fields=("username","email","password")

class UserProfileInfoForms(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=("portfolio_site","profile_pic")

learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForms


from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,"basicapp/index.html")

@login_required
def special(request):
    return HttpResponse("Logged in success,Nice...")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))



def register(request):

    registered=False

    if request.method == "POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForms(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user #Since it has OneToOne relationship.Mentioned in the models

            if "profile_pic" in request.FILES:
                profile.profile_pic=request.FILES["profile_pic"]

            profile.save()

            registered=True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForms()

    return render(request,"basicapp/registration.html",{"user_form":user_form,
                                                        "profile_form":profile_form,
                                                        "registered":registered})


def user_login(request):
    if request.method == "POST":
        username=request.POST.get("username") #username is the name of the "input field" and we are using "get" method because it is just a simple form
        password=request.POST.get("password") #Getting the password and the above method is done

        user=authenticate(username=username,password=password) # It authenticates the user for us.

        if user:
            if user.is_active:# checking if user is active or not
                login(request,user)#Logging in user
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT IS NOT ACTIVE')
        else:
            print("Someone tried to login and failed")
            print("username:{} and password:{}".format(username,password))
            return HttpResponse("INVALID LOGIN DETAILS SUPPLIED")
    else:
        return render(request,"basicapp/login.html")

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url "index" %}">DJANGO</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url "admin:index" %}">Admin<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "basicapp:register" %}">Register</a>
          </li>

          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url "user_logout" %}">Logout</a>
            </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url "basicapp:user_login" %}">Login</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}

    </div>
  </body>
</html>

learning_users/templates/basicapp/index.html
{% extends "basicapp/base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to Level5</h1>
    <h2>Home Page</h2>
  </div>
{% endblock %}

learning_users/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Login Here</h1>
    <form action="{% url 'basicapp:user_login' %}" method="POST">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" value="Login">
    </form>
  </div>
{% endblock %}

learning_users/templates/basicapp/registration.html
{% extends "basicapp/base.html" %}
{% load staticfiles %} <!--It is used for getting the static files from static folder-->

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank You for Registering</h1>
    {% else %}
      <h1>Register Here</h1>
      <h2>Fill out the form </h2>

      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <table>
          {{ user_form.as_table }}
          {{ profile_form.as_table}}            
        </table>
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>
{% endblock %}